[package]
name = "yew-sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
wasm-bindgen = "0.2.87"
weblog = "0.3.0"
yew = { version = "0.20", features = ["csr"] }
